/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Viatico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDWIN
 */
public class FrmDepositarViatico extends javax.swing.JFrame {
    /*private DefaultTableModel dtm;
    private Object[] o=new Object[4];*/
    /**
     * Creates new form FrmDepositarViatico
     */
    public FrmDepositarViatico() {
        /*initComponents();
        dtm= (DefaultTableModel) jMovimientos.getModel();*/
        initComponents();
        this.jMovimientos.setModel(modelo);
        this.modelo.addColumn("Codigo de tesorero");
        this.modelo.addColumn("Codigo Destinatario");
        this.modelo.addColumn("Codigo Solicitud de Viatico");
        this.modelo.addColumn("Monto");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCodigoTesorero = new javax.swing.JTextField();
        tfCodigoDestinatario = new javax.swing.JTextField();
        tfCodigoSolicitud = new javax.swing.JTextField();
        tfMontoDeposito = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMovimientos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfBusquedaDeposito = new javax.swing.JTextField();
        btnEditarDeposito = new javax.swing.JButton();
        btnEliminarDeposito = new javax.swing.JButton();
        btnBuscarDeposito = new javax.swing.JButton();
        btnNuevoDeposito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deposito de Viatico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo Tesorero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 100, -1));

        jLabel2.setText("Codigo Solicitud de Viatico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setText("Monto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel4.setText("Codigo Destinatario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        tfCodigoTesorero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoTesoreroActionPerformed(evt);
            }
        });
        jPanel1.add(tfCodigoTesorero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, -1));
        jPanel1.add(tfCodigoDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, -1));
        jPanel1.add(tfCodigoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 150, -1));
        jPanel1.add(tfMontoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save_as.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMovimientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jMovimientos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 83, 625, 284));

        jLabel5.setText("Busqueda:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 75, 20));
        jPanel2.add(tfBusquedaDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 176, 30));

        btnEditarDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/layer_edit.png"))); // NOI18N
        btnEditarDeposito.setText("Editar");
        btnEditarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        btnEliminarDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        btnEliminarDeposito.setText("Eliminar");
        btnEliminarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        btnBuscarDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/find.png"))); // NOI18N
        btnBuscarDeposito.setText("Buscar");
        btnBuscarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        btnNuevoDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pencil_add.png"))); // NOI18N
        btnNuevoDeposito.setText("Nuevo");
        btnNuevoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo = new DefaultTableModel();
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        /*String codTe=tfCodigoTesorero.getText();
        String codDesti=tfCodigoDestinatario.getText();
        String codSoli=tfCodigoSolicitud.getText();
        Viatico monto=new Viatico();
        monto.setMontoViatico(Double.parseDouble(tfMontoDeposisto.getText()));
        
        o[0]=codTe;
        o[1]=codDesti;
        o[2]=codSoli;
        o[3]=monto.getMontoViatico();
        dtm.addRow(o);*/
        
        this.modelo.addRow(new Object[]{
            this.tfCodigoTesorero.getText(),
            this.tfCodigoDestinatario.getText(),
            this.tfCodigoSolicitud.getText(),
            this.tfMontoDeposito.getText(),
        });
    
        JOptionPane.showMessageDialog(this, "El deposito de viatico se ha realizado correctamente.");
        //LIMPIAR
        tfCodigoTesorero.setText("");
        tfCodigoDestinatario.setText("");
        tfCodigoSolicitud.setText("");
        tfMontoDeposito.setText("");
        
    }//GEN-LAST:event_btnGuardarActionPerformed
    int filas;
    private void tfCodigoTesoreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoTesoreroActionPerformed
        
        
    }//GEN-LAST:event_tfCodigoTesoreroActionPerformed

    private void btnEditarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDepositoActionPerformed
        String []datos=new String[4];
        datos[0]=tfCodigoTesorero.getText();
        datos[1]=tfCodigoDestinatario.getText();
        datos[2]=tfCodigoSolicitud.getText();
        datos[3]=tfMontoDeposito.getText();
        
        for(int i=0; i<jMovimientos.getColumnCount();i++){
            modelo.setValueAt(datos[i], filas, i);
        }
    }//GEN-LAST:event_btnEditarDepositoActionPerformed

    private void btnNuevoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDepositoActionPerformed
        
        
        //LIMPIAR
        tfCodigoTesorero.setText("");
        tfCodigoDestinatario.setText("");
        tfCodigoSolicitud.setText("");
        tfMontoDeposito.setText("");
    }//GEN-LAST:event_btnNuevoDepositoActionPerformed

    private void btnEliminarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepositoActionPerformed
        int fila_seleccionada = jMovimientos.getSelectedRow();
        if(fila_seleccionada>=0){
            modelo.removeRow(fila_seleccionada);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila por favor");
        }
        tfCodigoTesorero.setText("");
        tfCodigoDestinatario.setText("");
        tfCodigoSolicitud.setText("");
        tfMontoDeposito.setText("");
    }//GEN-LAST:event_btnEliminarDepositoActionPerformed

    private void jMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMovimientosMouseClicked
        int fila_seleccionada = jMovimientos.getSelectedRow();
        tfCodigoTesorero.setText(jMovimientos.getValueAt(fila_seleccionada, 0).toString());
        tfCodigoDestinatario.setText(jMovimientos.getValueAt(fila_seleccionada, 1).toString());
        tfCodigoSolicitud.setText(jMovimientos.getValueAt(fila_seleccionada, 2).toString());
        tfMontoDeposito.setText(jMovimientos.getValueAt(fila_seleccionada, 3).toString()); 
        filas=fila_seleccionada;
    }//GEN-LAST:event_jMovimientosMouseClicked

    private void btnBuscarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepositoActionPerformed
        
    }//GEN-LAST:event_btnBuscarDepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDepositarViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDepositarViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDepositarViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDepositarViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDepositarViatico().setVisible(true);
            }
        });
    }
    private void Limpiar() {
        tfCodigoTesorero.setText("");
        tfCodigoDestinatario.setText("");
        tfCodigoSolicitud.setText("");
        tfMontoDeposito.setText("");
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDeposito;
    private javax.swing.JButton btnEditarDeposito;
    private javax.swing.JButton btnEliminarDeposito;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoDeposito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jMovimientos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBusquedaDeposito;
    private javax.swing.JTextField tfCodigoDestinatario;
    private javax.swing.JTextField tfCodigoSolicitud;
    private javax.swing.JTextField tfCodigoTesorero;
    private javax.swing.JTextField tfMontoDeposito;
    // End of variables declaration//GEN-END:variables
}
