
package Formularios;
import javax.swing.table.DefaultTableModel;
import Clases.DocumentoAcreditadorGasto;
import EstructuraDeDatos.ArregloDocumentoAcreditadorGasto;
import Interfacez.IDocumentoAcreditadorGasto;
import javax.swing.JTable;
import javax.swing.table.TableModel;
public class FrmRealizarRendicionCuentas2 extends javax.swing.JFrame {
    DefaultTableModel dtm1=new DefaultTableModel();
    Object[] o=new Object[5];
    ArregloDocumentoAcreditadorGasto dag1=new ArregloDocumentoAcreditadorGasto();
    
    public FrmRealizarRendicionCuentas2() {
        initComponents();
        dtm1=(DefaultTableModel)jTRealizarRC.getModel();
        getDTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSolicitudV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCodigoDAG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRealizarRC = new javax.swing.JTable();
        btnAgregarDoc = new javax.swing.JButton();
        btnEliminarDoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfTipoDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFechaG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMontoG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendición de Cuentas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código Solicitud Viático:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        jPanel1.add(tfSolicitudV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 215, -1));

        jLabel2.setText("Código DAG:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 80, -1));
        jPanel1.add(tfCodigoDAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 215, -1));

        jTRealizarRC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Solicitud Viatico", "Código DAG", "Tipo documento", "Fecha gasto", "Monto gasto"
            }
        ));
        jScrollPane1.setViewportView(jTRealizarRC);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 760, 300));

        btnAgregarDoc.setText("Agregar Documento");
        btnAgregarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, 30));

        btnEliminarDoc.setText("Eliminar");
        btnEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 80, 30));

        jLabel3.setText("Tipo Documento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        jPanel1.add(tfTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, -1));

        jLabel4.setText("Fecha Gasto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        jPanel1.add(tfFechaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, -1));

        jLabel5.setText("Monto Gasto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        jPanel1.add(tfMontoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Eliminar Documento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel7.setText("Número de fila:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));
        jPanel1.add(tfEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocActionPerformed
        // TODO add your handling code here:
        
        dag1.addDocumentoAcreditadorGasto(new DocumentoAcreditadorGasto(null,
                Double.parseDouble(tfMontoG.getText()),tfFechaG.getText(),tfCodigoDAG.getText()));
        o[0]=tfSolicitudV.getText();
        o[1]=tfCodigoDAG.getText();
        o[2]=tfTipoDoc.getText();
        o[3]=tfFechaG.getText();
        o[4]=tfMontoG.getText();
        dtm1.addRow(o);
        
        
    }//GEN-LAST:event_btnAgregarDocActionPerformed

    private void btnEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocActionPerformed
        // TODO add your handling code here:
        int er=(Integer.parseInt(tfEliminar.getText()));
        er--;
        dtm1.removeRow(er);
    }//GEN-LAST:event_btnEliminarDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarRendicionCuentas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarRendicionCuentas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarRendicionCuentas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarRendicionCuentas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRealizarRendicionCuentas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDoc;
    private javax.swing.JButton btnEliminarDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTRealizarRC;
    private javax.swing.JTextField tfCodigoDAG;
    private javax.swing.JTextField tfEliminar;
    private javax.swing.JTextField tfFechaG;
    private javax.swing.JTextField tfMontoG;
    private javax.swing.JTextField tfSolicitudV;
    private javax.swing.JTextField tfTipoDoc;
    // End of variables declaration//GEN-END:variables

    public TableModel getDTabla() {
        return jTRealizarRC.getModel();
    }

    
}
